version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - dupword
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - godox
    - ireturn
    - mnd
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - promlinter
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 15
    # https://github.com/golangci/golangci-lint/issues/2610
    revive:
      confidence: 0.8
      severity: warning
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        source: ^//go:generate
      # Do not require error checking on calls to gin's ctx.Error - it just
      # returned the internally wrapped error object for what is handled by
      # logging middleware.
      - path: frontend/
        source: \.(AbortWith)?Error\(.+
      - linters:
          - staticcheck
        path: backends/
        text: 'ST1000:'
      - linters:
          - staticcheck
        path: app/
        text: 'ST1000:'
      - linters:
          - staticcheck
        path: config/
        text: 'ST1000:'
      - linters:
          - staticcheck
        path: internal/
        text: 'ST1000:'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
